on: [workflow_dispatch]

jobs:
  test_bn_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Get build number
        id: get-build
        uses: mlilback/build-number@v1
        with:
          base: 100
          run-id: "${{ github.run_number }}"
      - name: get the build number
        run: echo "${BUILD_NUMBER}"
